In [3]:
import numpy as np
import sys
import time

In [6]:
# numpy array is faster than python list

SIZE = 1000000
l1 = range(SIZE)
l2 = range(SIZE)
a1 = np.arange(SIZE)
a2 =np.arange(SIZE)

start =time.time()
res = [(x+y) for x,y in zip(l1,l2)]
print("list: ",(time.time()-start)*1000)

start = time.time()
res = a1+a2
print("numpy array: ",(time.time()-start)*1000)


list:  192.87848472595215
numpy array:  17.879486083984375


In [7]:
#numpy array is also more convenient to use

a1 =np.array([1,2,3])
a2 = np.array([4,5,6])
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [12]:
a = np.array([5,6,7])
a[0]
a[1]
a.ndim


1

In [15]:
a= np.array([[1,2],[3,4],[5,6]])
a.ndim
a.itemsize
a.dtype

dtype('int32')

In [16]:
a= np.array([[1,2],[3,4],[5,6]], dtype =np.float64)
a.itemsize

8

In [18]:
a.size #total no of elements
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [19]:
a.shape

(3, 2)

In [20]:
a[0]

array([1., 2.])

In [21]:
a= np.array([[1,2],[3,4],[5,6]], dtype =complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [22]:
#intialize a array with a specific no , here 0
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.ones((3,4), dtype = np.int32)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [26]:
np.arange(1,5)

array([1, 2, 3, 4])

In [27]:
np.linspace(1,5,10) #generate 10 numbers b/w 1 and 5 which are lineary spaced

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [29]:
#reshaping array
a= np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
a.shape

(3, 2)

In [32]:
a.reshape(2,3) #doesnt modify original array

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
#flattening a array == making it 1D
a.ravel() #doesn't modify the original array


array([1, 2, 3, 4, 5, 6])

In [35]:
#min and max function
a.min()
a.max()

6

In [36]:
a.sum() #return sum of all elements

21

In [39]:
a.sum(axis =0) #sum of elements in 0 or columns

array([ 9, 12])

In [40]:
a.sum(axis =1) #sum of elements row wise

array([ 3,  7, 11])

In [41]:
np.sqrt(a) #sqrt of all elemets of array

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [42]:
#standard deviation
np.std(a)

1.707825127659933

In [47]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a+b
a*b
a/b
a.dot(b) #matrix multiplication

array([[19, 22],
       [43, 50]])