In [2]:
import numpy as np 

In [3]:
#python list
n = [6,7,8] 
n[0:2] #slicing


[6, 7]

In [4]:
#numpy array
a =np.array([6,7,8])
a[0:2] #slicing
a[-1]

8

In [5]:
# 2D array
a = np.array([[6,7,8], [1,2,3], [4,5,9]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [4, 5, 9]])

In [6]:
a[1,2] #accessing elements from 2D array using indexing a[i,j] where i =row and j =column


3

In [7]:
#slicing in 2D array
a[0:2,2] #traverse from 0 row and 1 row and print their element at 2nd index

array([8, 3])

In [8]:
a[-1] #prints last row

array([4, 5, 9])

In [9]:
a[-1,0:2] #row =-1, column 0,1

array([4, 5])

In [10]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [5, 9]])

In [11]:
#printing each row of array
for i in a:
    print(i)

[6 7 8]
[1 2 3]
[4 5 9]


In [12]:
#flattening the array, printing all elemets as if 1D array
for i in a.flat:
    print(i)

6
7
8
1
2
3
4
5
9


In [13]:
#stacking 2 arrays together
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [14]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [15]:
# vertical stacking
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [16]:
# horizontal stacking
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [17]:
a = np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [18]:
#spliting the array
np.hsplit(a,3) #spliting the array horizontally into 3 arrays

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [19]:
np.vsplit(a,2) #vertically splitting the array into 2 array

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [20]:
#idexing with boolean array
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
b = a>4 
b 

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [24]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [26]:
a[b] = -1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])